<?php

/**
 * @file
 * Handles the creation and display of simple XML objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_solution_pack_xml_menu() {
  $items = array();
  $items['admin/islandora/solution_pack_config/xml'] = array(
    'title' => 'Simple XML Solution Pack',
    'description' => 'Configure the Simple XML Object Solution Pack.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_solution_pack_xml_admin'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_theme().
 *
 * We supply a pattern so we can overide templates at the theme level if needed.
 * We can append a pid to a template and the new template file will be called
 * (the pid's colon should be replaced with a dash).
 * An example template might be named:
 *   "islandora-simple-xml--islandora-100.tpl.php".
 */
function islandora_solution_pack_xml_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_solution_pack_xml_default' => array(
      'template' => 'theme/islandora-solution-pack-xml-default',
      'file' => 'theme/theme.inc',
      'pattern' => 'islandora_solution_pack_xml__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_solution_pack_xml_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_solution_pack_xml');
  // Web ARChive Content Model.
  $simple_xml_content_model = $connection->repository->constructObject('islandora:sp_simple_xml');
  $simple_xml_content_model->owner = 'fedoraAdmin';
  $simple_xml_content_model->label = 'Islandora Simple XML Content Model';
  $simple_xml_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $simple_xml_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_simple_xml_ds_composite_model.xml", FALSE);
  $simple_xml_content_model->ingestDatastream($datastream);
  // Simple XML Collection.
  $simple_xml_collection = $connection->repository->constructObject('islandora:sp_simple_xml_collection');
  $simple_xml_collection->owner = 'fedoraAdmin';
  $simple_xml_collection->label = 'Simple XML Collection';
  $simple_xml_collection->models = 'islandora:collectionCModel';
  $simple_xml_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $simple_xml_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_simple_xml_collection_policy.xml", FALSE);
  $simple_xml_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $simple_xml_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $simple_xml_collection->ingestDatastream($datastream);
  return array(
    'islandora_solution_pack_xml' => array(
      'title' => 'Islandora Simple XML',
      'objects' => array(
        $simple_xml_content_model,
        $simple_xml_collection,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_solution_pack_xml_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_solution_pack_xml');
  return array(
    'Islandora Simple XML Object MODS form' => array(
      'form_file' => "$module_path/xml/islandora_simple_xml_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_solution_pack_xml_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_simple_xml_mods_form' => array(
      'content_model' => 'islandora:sp_simple_xml',
      'form_name' => 'Islandora Simple XML Object MODS form',
      'dsid' => 'MODS',
      'title_field' => array(
        'titleInfo', 'title',
      ),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'cleanup_mods.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_cmodel_pid_islandora_ingest_steps().
 */
function islandora_solution_pack_xml_islandora_sp_simple_xml_islandora_ingest_steps() {
  return array(
    'islandora_solution_pack_xml_obj_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_solution_pack_xml_xml_upload_form',
      'module' => 'islandora_solution_pack_xml',
      'file' => 'includes/xml_object_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_solution_pack_xml_islandora_sp_simple_xml_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_solution_pack_xml_default', array('islandora_object' => $object));
  return array('' => $output);
}

