<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_simple_xml_viewer_menu() {
  return array(
    'admin/islandora/islandora_viewers/simple_xml' => array(
      'title' => 'Simple XML Viewer',
      'description' => 'Configure the Simple XML viewer.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_simple_xml_viewer_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_simple_xml_viewer_theme() {
  return array(
    'islandora_simple_xml' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-simple-xml-viewer',
      'variables' => array(
        'islandora_object' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_simple_xml_viewer_islandora_viewer_info() {
  return array(
    'islandora_simple_xml' => array(
      'label' => t('Islandora Simple XML Viewer'),
      'description' => t('A simple XML viewer for Islandora.'),
      'configuration' => 'admin/islandora/islandora_viewers/simple_xml',
      'callback' => 'islandora_simple_xml_viewer_callback',
      'model' => array(
        'islandora:sp_simple_xml'),
      'mimetype' => array('application/xml'),
    ),
  );
}

/**
 * Callback function for the viewer.
 *
 * @param array $params
 *   The params for the theme function 'islandora_pdfjs'.
 *
 * @param IslandoraAbstractObject $fedora_object
 *   The object that we are viewing.
 *
 * @return string
 *   HTML repersentation of the pdf.js Reader.
 */
function islandora_simple_xml_viewer_callback(array $params, $fedora_object = NULL) {
  $dsid = NULL;
  if (isset($params['dsid']) && !empty($params['dsid']) && isset($fedora_object[$dsid])) {
    $dsid = $params['dsid'];
  }
  else {
    if (isset($fedora_object['OBJ'])) {
      $dsid = 'OBJ';
    }
    elseif (isset($fedora_object['OBJ']) && $fedora_object['OBJ']->mimetype == 'application/xml') {
      $dsid = 'OBJ';
    }
  }
  if ($dsid && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $fedora_object[$dsid])) {
    return theme('islandora_simple_xml', array('fedora_object' => $fedora_object, 'dsid' => $dsid));
  }
}
