<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_simple_xml_viewer_menu() {
  return array(
    'admin/islandora/islandora_viewers/simple_xml' => array(
      'title' => 'Simple XML Viewer',
      'description' => 'Configure the Simple XML viewer.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_simple_xml_viewer_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_simple_xml_viewer_theme() {
  return array(
    'islandora_simple_xml_viewer' => array(
      'file' => 'theme/theme.inc',
      'template' => 'theme/islandora-simple-xml-viewer',
      'variables' => array(
        'islandora_object' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_simple_xml_viewer_islandora_viewer_info() {
  return array(
    'islandora_simple_xml' => array(
      'label' => t('Islandora Simple XML Viewer'),
      'description' => t('A simple XML viewer for Islandora.'),
      'configuration' => 'admin/islandora/islandora_viewers/simple_xml',
      'callback' => 'islandora_simple_xml_viewer_callback',
      'model' => array(
        'islandora:sp_simple_xml'),
      'mimetype' => array('application/xml'),
    ),
  );
}

/**
 * Callback function for the viewer.
 *
 * @param array $params
 *   The params for the theme function 'islandora_simple_xml_viewer'.
 *
 * @param IslandoraAbstractObject $fedora_object
 *   The object that we are viewing.
 *
 * @return string
 *   HTML repersentation of the Simple XML Viewer.
 */
function islandora_simple_xml_viewer_callback(array $params, $islandora_object = NULL) {
  if (isset($islandora_object['OBJ']) && $islandora_object['OBJ']->mimetype == 'application/xml') {
    if (islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['OBJ'])) {
      return theme('islandora_simple_xml_viewer', array('islandora_object' => $islandora_object));
    }
  }
}
