<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_context_registry().
 */
function islandora_simple_xml_context_context_registry() {
  return array(
    'conditions' => array(
      'islandora_simple_xml_context_condition_root_element' => array(
        'title' => t('Islandora Simple XML root element'),
        'description' => t("Choose this condition if you want to inspect an XML OBJ datastream's root element"),
        'plugin' => 'islandora_simple_xml_context_condition_root_element',
      ),
    ),
    'reactions' => array(
      'islandora_simple_xml_context_reaction_use_viewer' => array(
        'title' => t('Use an Islandora Simple XML viewer'),
        'description' => t("Use an Islandora Simple XML viewer"),
        'plugin' => 'islandora_simple_xml_context_reaction_use_viewer',
      ),
    ),
  );
}

/**
 * Implements hook_ctools_plugin_api().
 */
function islandora_simple_xml_context_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_context_plugins().
 */
function islandora_simple_xml_context_context_plugins() {
  $plugins = array();
  $plugins['islandora_simple_xml_context_condition_root_element'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'islandora_simple_xml_context') . '/plugins',
      'file' => 'islandora_simple_xml_context_condition_root_element.inc',
      'class' => 'IslandoraSimpleXmlContextConditionRootElement',
      'parent' => 'context_condition',
    ),
  );
  $plugins['islandora_simple_xml_context_reaction_use_viewer'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'islandora_simple_xml_context') . '/plugins',
      'file' => 'islandora_simple_xml_context_reaction_use_viewer.inc',
      'class' => 'IslandoraSimpleXmlContextReactionUseViewer',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function _islandora_simple_xml_context_islandora_sp_simple_xml_islandora_view_object(AbstractObject $object, $page_number, $page_size) {
  if ($plugin = context_get_plugin('condition', 'islandora_simple_xml_context_condition_root_element')) {
    $plugin->execute($object);
  }
  return array();
}


/**
 * Preprocessor for theme('page').
 */
function islandora_simple_xml_context_preprocess_islandora_solution_pack_xml_default(&$vars) {
  $islandora_object = $vars['islandora_object'];
  if ($plugin = context_get_plugin('reaction', 'islandora_simple_xml_context_reaction_use_viewer')) {
    if ($viewer = $plugin->execute($islandora_object)) {
      $vars['islandora_content'] = $viewer;
    }
  }
}
