<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_context_registry().
 */
function islandora_simple_xml_context_context_registry() {
  return array(
    'conditions' => array(
      'islandora_simple_xml_context_condition_root_element' => array(
        'title' => t('Islandora Simple XML root element'),
        'description' => t("Choose this condition if you want to inspect an XML OBJ datastream's root element"),
        'plugin' => 'islandora_simple_xml_context_condition_root_element',
      ),
      'islandora_simple_xml_context_condition_namespaces' => array(
        'title' => t('Islandora Simple XML namespaces'),
        'description' => t("Choose this condition if you want to inspect an XML OBJ datastream's namespaces. The namespaces can be registered anywhere in the document."),
        'plugin' => 'islandora_simple_xml_context_condition_namespaces',
      ),
    ),
    'reactions' => array(
      'islandora_simple_xml_context_reaction_use_viewer' => array(
        'title' => t('Use an Islandora Simple XML viewer'),
        'description' => t("Use an Islandora Simple XML viewer"),
        'plugin' => 'islandora_simple_xml_context_reaction_use_viewer',
      ),
      'islandora_simple_xml_context_reaction_use_format' => array(
       'title' => t('Text format to use with an Islandora Simple XML Viewer'),
        'description' => t("Use a text format with an Islandora Simple XML viewer"),
        'plugin' => 'islandora_simple_xml_context_reaction_use_format',
      ),
    ),
  );
}

/**
 * Implements hook_ctools_plugin_api().
 */
function islandora_simple_xml_context_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_context_plugins().
 */
function islandora_simple_xml_context_context_plugins() {
  $plugins = array();
  $plugins['islandora_simple_xml_context_condition_root_element'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'islandora_simple_xml_context') . '/plugins',
      'file' => 'islandora_simple_xml_context_condition_root_element.inc',
      'class' => 'IslandoraSimpleXmlContextConditionRootElement',
      'parent' => 'context_condition',
    ),
  );
  $plugins['islandora_simple_xml_context_condition_namespaces'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'islandora_simple_xml_context') . '/plugins',
      'file' => 'islandora_simple_xml_context_condition_namespaces.inc',
      'class' => 'IslandoraSimpleXmlContextConditionNamespaces',
      'parent' => 'context_condition',
    ),
  );
  $plugins['islandora_simple_xml_context_reaction_use_viewer'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'islandora_simple_xml_context') . '/plugins',
      'file' => 'islandora_simple_xml_context_reaction_use_viewer.inc',
      'class' => 'IslandoraSimpleXmlContextReactionUseViewer',
      'parent' => 'context_reaction',
    ),
  );
  $plugins['islandora_simple_xml_context_reaction_use_format'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'islandora_simple_xml_context') . '/plugins',
      'file' => 'islandora_simple_xml_context_reaction_use_format.inc',
      'class' => 'IslandoraSimpleXmlContextReactionUseFormat',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_CMODEL_PID_islandora_object_access().
 */
function islandora_simple_xml_context_islandora_sp_simple_xml_islandora_object_access($op, $object, $user) {
  if ($plugin = context_get_plugin('condition', 'islandora_simple_xml_context_condition_root_element')) {
    $plugin->execute($object);
  }
  if ($plugin = context_get_plugin('condition', 'islandora_simple_xml_context_condition_namespaces')) {
    $plugin->execute($object);
  }
  return NULL;
}
